language: php

php:
  - '7.1'

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: phpunit --coverage-clover=coverage.xml

after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email: false